apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmqbroker-slave
  labels:
    app: rmqbroker-slave
#  namespace: default
spec:
  serviceName: rmqbroker-slave
  replicas: 1
  selector:
    matchLabels:
      app: rmqbroker-slave
  template:
    metadata:
      labels:
        app: rmqbroker-slave
    spec:
      containers:
        - name: rmqbroker-slave
          image: nexus3.onap.org:10001/rocketmqinc/rocketmq:4.4.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 2000Mi
            requests:
              cpu: 400m
              memory: 2000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: NAMESRV_ADDR
              value: rocketmq:9876
            - name: JAVA_OPT_EXT
              # Ôö¼Ódebug
              value: -Xdebug -Xrunjdwp:transport=dt_socket,address=9555,server=y,suspend=n  -Duser.home=/opt -server  -Xms1700m -Xmx1700m
          command: ["/bin/bash","mqbroker","-c","/etc/rocketmq/broker-s.conf","-n","rocketmq:9876","autoCreateTopicEnable=true"]
          ports:
            - containerPort: 10919
            - containerPort: 10921
            - containerPort: 10922
          volumeMounts:
            - name: vol-logs
              mountPath: /opt/logs
            - name: vol-store
              mountPath: /opt/store
            - name: vol-broker-s
              mountPath: /etc/rocketmq/broker-s.conf
      volumes:
        - name: vol-logs
          hostPath:
            path: /www/k8s/foxdev/rocketmq/logs-b-s
            type: Directory
        - name: vol-store
          hostPath:
              path: /www/k8s/foxdev/rocketmq/store-b-s
              type: Directory
        - name: vol-broker-s
          hostPath:
              path: /www/k8s/foxdev/rocketmq/conf/broker-s.conf
              type: File
